/**
 * Generates report.md, territory-metrics.csv, nation-metrics.csv, and events.csv
 * from a completed RunResult.
 */
import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { RunResult, TickSnapshot } from './types';

// Tick markers included in the summary tables.
const REPORT_TICKS = [0, 1, 2, 5, 10, 15, 20, 25, 30, 40, 50];

function pct(n: number): string { return (n * 100).toFixed(1) + '%'; }
function f3(n: number): string { return n.toFixed(3); }
function pad(s: string, w: number): string { return s.padEnd(w); }

// ── report.md ────────────────────────────────────────────────────────────────

export function generateReport(result: RunResult, outputDir: string): void {
  const { scenario, snapshots } = result;
  const finalSnap = snapshots[snapshots.length - 1]!;
  const ticks = scenario.ticks;

  // Which territories changed ownership at some point?
  const changed = new Set<string>();
  const t0 = snapshots[0]!.territories;
  for (const [id, snap] of Object.entries(finalSnap.territories)) {
    if (snap.ownerId !== t0[id]?.ownerId) changed.add(id);
  }
  // Also include territories that had any revolt or high unrest.
  for (const snap of snapshots) {
    for (const [id, t] of Object.entries(snap.territories)) {
      if (t.isInRevolt || t.unrest > 0.3) changed.add(id);
    }
  }

  const lines: string[] = [];

  lines.push(`# Scenario: ${scenario.name}`);
  if (scenario.description) lines.push(`\n> ${scenario.description}`);
  lines.push(`\n**Ticks run:** ${ticks}`);
  lines.push(`**Nations:** ${scenario.world.nations.length}`);
  lines.push(`**Scripted actions:** ${(scenario.actions ?? []).length}`);

  // ── Final state per nation ──────────────────────────────────────────────────
  lines.push('\n---\n\n## Nation Summary — Final State\n');
  lines.push('| Nation | Territories | Avg Unrest | Max Unrest | Revolts at Final |');
  lines.push('|---|---|---|---|---|');
  for (const n of scenario.world.nations) {
    const ownedIds = Object.entries(finalSnap.territories)
      .filter(([, t]) => t.ownerId === n.id)
      .map(([id]) => id);
    const unrests = ownedIds.map((id) => finalSnap.territories[id]!.unrest);
    const avg = unrests.length ? unrests.reduce((a, b) => a + b, 0) / unrests.length : 0;
    const max = unrests.length ? Math.max(...unrests) : 0;
    const revolting = ownedIds.filter((id) => finalSnap.territories[id]!.isInRevolt).length;
    lines.push(`| ${n.name} | ${ownedIds.join(', ') || '—'} | ${pct(avg)} | ${pct(max)} | ${revolting} |`);
  }

  // ── Per-territory unrest history ────────────────────────────────────────────
  const interestingTerrs = [...changed].filter((id) =>
    snapshots.some((s) => s.territories[id]?.ownerId !== null),
  );

  lines.push('\n---\n\n## Unrest & Equilibrium — Key Territories\n');
  const snapTicks = REPORT_TICKS.filter((t) => t <= ticks);

  for (const tid of interestingTerrs) {
    lines.push(`### ${tid}\n`);
    lines.push('| Tick | Owner | Unrest | Eq. | Shock | Compat | Infra | Distance |');
    lines.push('|------|-------|--------|-----|-------|--------|-------|----------|');
    for (const t of snapTicks) {
      const snap = snapshots[t];
      if (!snap) continue;
      const ts = snap.territories[tid];
      if (!ts) continue;
      const c = ts.causes;
      lines.push(
        `| T${t} | ${ts.ownerId ?? '—'} | ${pct(ts.unrest)} | ${pct(ts.equilibrium)} |` +
        ` ${f3(ts.ownershipShock)} | ${ts.compatTotal !== null ? f3(ts.compatTotal) : '—'} |` +
        ` ${c ? f3(c.infrastructureBonus) : '—'} | ${c ? f3(c.distancePressure) : '—'} |`,
      );
    }
    lines.push('');
  }

  // ── Revolt events ──────────────────────────────────────────────────────────
  const allEvents = snapshots.flatMap((s) => s.events);
  if (allEvents.length > 0) {
    lines.push('---\n\n## Event Timeline\n');
    lines.push('| Tick | Event |');
    lines.push('|------|-------|');
    for (const e of allEvents) {
      lines.push(`| T${e.tick} | ${e.message} |`);
    }
  }

  // ── Chart list ─────────────────────────────────────────────────────────────
  lines.push('\n---\n\n## Charts\n');
  lines.push('- `charts/unrest-over-time.png` — Unrest per territory over all ticks');
  for (const tid of interestingTerrs) {
    lines.push(`- \`charts/equilibrium-${tid}.png\` — Equilibrium component breakdown for ${tid}`);
  }
  lines.push('- `charts/nation-culture-drift.png` — Nation culture axis drift over time');
  lines.push('\n*Generated by the WAR simulation harness.*');

  writeFileSync(join(outputDir, 'report.md'), lines.join('\n') + '\n');
  console.log('  ✓ report.md');
}

// ── CSVs ─────────────────────────────────────────────────────────────────────

export function generateCSVs(result: RunResult, outputDir: string): void {
  const { snapshots } = result;

  // territory-metrics.csv
  const terrHeader = [
    'tick', 'territory_id', 'owner_id', 'unrest', 'equilibrium',
    'conquest_shock', 'base', 'compat_pressure', 'distance_pressure',
    'infra_bonus', 'overexpansion', 'rapid_expansion', 'is_in_revolt', 'compat_total',
  ].join(',');

  const terrRows: string[] = [terrHeader];
  for (const snap of snapshots) {
    for (const [tid, ts] of Object.entries(snap.territories)) {
      const c = ts.causes;
      terrRows.push([
        snap.tick, tid, ts.ownerId ?? '',
        ts.unrest.toFixed(6), ts.equilibrium.toFixed(6),
        ts.ownershipShock.toFixed(6),
        c ? c.base.toFixed(6) : '',
        c ? c.compatibilityPressure.toFixed(6) : '',
        c ? c.distancePressure.toFixed(6) : '',
        c ? c.infrastructureBonus.toFixed(6) : '',
        c ? c.overexpansionPressure.toFixed(6) : '',
        c ? c.recentConquestPressure.toFixed(6) : '',
        ts.isInRevolt ? '1' : '0',
        ts.compatTotal !== null ? ts.compatTotal.toFixed(6) : '',
      ].join(','));
    }
  }
  writeFileSync(join(outputDir, 'territory-metrics.csv'), terrRows.join('\n') + '\n');

  // nation-metrics.csv
  const natHeader = [
    'tick', 'nation_id', 'pop_stock', 'ind_stock', 'wealth_stock', 'army_size',
    'culture_individualist', 'culture_progressive', 'culture_militaristic', 'culture_expansionist', 'culture_family',
  ].join(',');

  const natRows: string[] = [natHeader];
  for (const snap of snapshots) {
    for (const [nid, ns] of Object.entries(snap.nations)) {
      const cu = ns.culture;
      natRows.push([
        snap.tick, nid,
        ns.stockpiles.population.toFixed(2), ns.stockpiles.industry.toFixed(2), ns.stockpiles.wealth.toFixed(2),
        '',  // armySize not in snapshot — acceptable gap for now
        cu ? cu.individualist.toFixed(6) : '',
        cu ? cu.progressive.toFixed(6) : '',
        cu ? cu.militaristic.toFixed(6) : '',
        cu ? cu.expansionist.toFixed(6) : '',
        cu ? (cu.primaryFamily ?? '') : '',
      ].join(','));
    }
  }
  writeFileSync(join(outputDir, 'nation-metrics.csv'), natRows.join('\n') + '\n');

  // events.csv
  const evtRows = ['tick,message'];
  for (const snap of snapshots) {
    for (const e of snap.events) {
      evtRows.push(`${e.tick},"${e.message.replace(/"/g, '""')}"`);
    }
  }
  writeFileSync(join(outputDir, 'events.csv'), evtRows.join('\n') + '\n');

  console.log('  ✓ territory-metrics.csv  nation-metrics.csv  events.csv');
}
